<?php
// Generated by Zend Framework 2
return array(
    'CourseSearch\Module'                      => __DIR__ . '//Module.php',
    'CourseSearch\Controller\CourseSearchController' => __DIR__ . '//src/CourseSearch/Controller/CourseSearchController.php',
    'CourseSearch\Form\CourseSearchForm'       => __DIR__ . '//src/CourseSearch/Form/CourseSearchForm.php',
    'CourseSearch\Model\Course'                => __DIR__ . '//src/CourseSearch/Model/Course.php',
    'CourseSearch\Model\CourseSearchInput'     => __DIR__ . '//src/CourseSearch/Model/CourseSearchInput.php',
    'CourseSearch\Model\CourseTable'           => __DIR__ . '//src/CourseSearch/Model/CourseTable.php',
    'CourseSearch\View\Helper\CourseSearchForm'      => __DIR__ . '//src/CourseSearch/View/Helper/CourseSearchForm.php',
);