<div id="courseDisplayingForbidden">
	<?php
	echo sprintf($this->translate(
		'Unfortunately %s forbids displaying the courses information on unisport<span class="rStyle">r</span>.'
	), $courseProvider);
	?>
	<?php echo $this->translate('You can try it with the directly link to the course below.'); ?>
</div>
<div id="courseLink">
	<?php echo $this->translate('Course') . ' ' . $course->title . ' ' . $this->translate('on the website of') . ' ' . $courseProvider . ':'; ?><br />
	<?php echo $course->url; ?>
</div>