<?php
use ITT\Util\Utility;
?>
<?php
$title = $course->title;
$this->headTitle($title);
?>
<?php
$titleMaxLength = 40;
$courseTitle = strlen($this->escapeHtml($course->title)) > $titleMaxLength
	? substr($this->escapeHtml($course->title), 0, $titleMaxLength) . '...'
	: $this->escapeHtml($course->title)
;
?>

<h1 id="pageTitle"><?php echo $title; ?></h1>

<div id="courseExpired">
<?php echo $this->translate('The course') . ' ' . $course->title . ' ' . $this->translate('is not available anymore') . '.'; ?>
</div>
<div class="clear"></div>