<?php
use ITT\Util\Utility;
use Catalog\Model\CourseTable;
?>
<?php
$titleMaxLength = 40;
$courseTitle = $this->escapeHtml($course->title);
$courseTitle = !empty($courseTitle)
	? $courseTitle
	: $this->translate('Untitled')
;
$courseTitleShorted = strlen($courseTitle) > $titleMaxLength
	? substr($courseTitle, 0, $titleMaxLength) . '...'
	: $courseTitle
;
?>
<?php
$this->headScript()
	->appendFile($this->basePath() . 'http://maps.googleapis.com/maps/api/js?key=' . $gMapsKey . '&sensor=false', 'text/javascript')
	->appendFile($this->basePath() . '/js/Log.js', 'text/javascript')
	->appendFile($this->basePath() . '/js/GMap.js', 'text/javascript')
;
?>

<h1 id="pageTitle"><?php echo $courseTitleShorted; ?></h1>
<?php
$courseDescription = $this->escapeHtml($course->description);
$courseLevel = Utility::getOneOrPair(
	$this->escapeHtml($course->uniLevelMin),
	$this->escapeHtml($course->uniLevelMax),
	' - '
);
$courseDate = Utility::getOneOrPair(
	$this->escapeHtml($course->startDate), $this->escapeHtml($course->endDate), ' - '
);
$courseWeekday = $this->escapeHtml($course->weekday);
$courseCity = $this->escapeHtml($course->city);
$courseTime = Utility::getOneOrPair(
	$this->escapeHtml($course->startTime), $this->escapeHtml($course->endTime), ' - '
);
$providerLabel = $this->escapeHtml($course->providerType) == 'university'
	? $this->translate('university')
	: $this->translate('partner')
;
$courseProvider = $this->escapeHtml($course->providerName);
$courseTrainer = str_replace('|||', ', ', $this->escapeHtml($course->trainers));
if (strrpos($courseTrainer, ', ') !== false) {
	$courseTrainer = substr_replace(
		$courseTrainer, ' ' . $this->translate('and') . ' ', strrpos($courseTrainer, ', '), strlen(', ')
	);
}
$courseSports = str_replace('|||', ', ', $this->escapeHtml($course->sports));
$courseLocation = $this->escapeHtml($course->location);
?>

<?php
$title = $courseTitleShorted;
$keywordsArray = array($this->translate('course'), $courseTitleShorted, $courseProvider, $courseCity,);
if (strcasecmp($courseSports, CourseTable::SPORT_TITLE_UNASSIGNED)) {
	array_unshift($keywordsArray, $courseSports);
}
$this->headMeta()->setName('keywords', implode(', ', $keywordsArray));
$metaDescriptionText = $this->translate('Course') . ' ' . $courseTitleShorted;
$metaDescriptionText .= !empty($courseTrainer)
	? ' ' . $this->translate('by') . ' ' . $courseTrainer
	: ''
;
$metaDescriptionText .= ' ' . $this->translate('at') . ' ' . $courseProvider;
$metaDescriptionText .= ' ' . $this->translate('in') . ' ' . $courseCity;
$this->headMeta()->setName('description', $metaDescriptionText);
$this->headTitle($title . ' ' . $this->translate('at') . ' ' . $courseProvider);
?>

<?php
if (!empty($course->courseID01)) {
	$courseID = $course->courseID01;
} else if (!empty($course->courseID02)) {
	$courseID = $course->courseID02;
} else {
	$courseID = null;
}
?>
<?php
$urlParams = array('id' => $this->escapeHtml($course->id), 'title' => $courseTitle);
$aURL = $this->url('course', $urlParams);
$aText = $courseTitle;
?>

<script type="text/javascript">
jQuery('document').ready(function() {
//	var address = 'TU-Sportzentrum Dovestraße Berlin';
	var address = '<?php echo $this->makeAddressGMapsFriendlier($courseLocation, $courseCity); ?>';
	var gMap = new GMap(address);
//	gMap.setLogging(true);
	gMap.showMap();
});
</script>

<div id="courseTitle">
	<a
		href="<?php echo $aURL; ?>"
		title="<?php echo $aText; ?>"
	><?php echo $aText; ?></a>
</div>
<div class="clear"></div>
<?php
$subViewParams = array(
	'course' => $course,
	'courseID' => $courseID,
	'courseDescription' => $courseDescription,
	'courseLevel' => $courseLevel,
	'courseDate' => $courseDate,
	'courseTime' => $courseTime,
	'courseWeekday' => $courseWeekday,
	'providerLabel' => $providerLabel,
	'courseProvider' => $courseProvider,
	'urlParams' => $urlParams,
	'aURL' => $aURL,
	'aText' => $aText,
	'uri' => $uri,
);

// variant 1
$dateTimeNow = new \DateTime('now');
$dateTimeCourseEndDate = new \DateTime($course->endDate);
$courseExpired = !($dateTimeCourseEndDate >= $dateTimeNow);
// variant 2
// $courseEndDate = date_create($course->endDate);
// $nowDate = date_create('now');
// $courseEndNowInterval = date_diff($nowDate, $courseEndDate);
// $courseExpired = $courseEndNowInterval->format('%R%a') < 0;

if ($course->providerStatus != 'inactive') {
	if (!$courseExpired) {
		echo $this->render('course/course/course-info.phtml', $subViewParams);
	} else {
		echo $this->render('course/course/course-expired.phtml', $subViewParams);
	}	
} else {
	echo $this->render('course/course/course-forbidden.phtml', $subViewParams);
}
?>

<div id="courseLink">
	<a
		href="<?php echo $course->url; ?>"
		title="<?php echo $courseProvider; ?>"
		rel="nofollow"
	><?php echo $this->translate('Course') . ' ' . $course->title . ' ' . $this->translate('on the website of') . ' ' . $courseProvider . ' ' . $this->translate('visit'); ?></a>
</div>
<div>
	<!-- AddThis Panel -->
	<?php
	echo $this->render('/partials/addthis-share-buttons.phtml', array(
		'url' => $uri,
	));
	?>
</div>