<?php
$title = $this->translate('List of cities with university sport courses');
$this->headMeta()->setName('keywords', implode(
	', ',
	array(
		$this->translate('cities'),
		$this->translate('list')
	)
));
$this->headMeta()->setName('description', $title);
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<ul id="catalogListCities" class="catalogList">
<?php foreach ($cities as $city) : ?>
	<li>
		<?php
		$aURL = $this->url('city',  array('city' => $this->escapeHtml($city->name)));
		$aText = $this->escapeHtml($city->name);
		?>
		<span><a href="<?php echo $aURL; ?>"><?php echo $aText; ?></a></span>
	</li>
<?php endforeach; ?>
</ul>