<?php
echo __FILE__;
$title = $this->translate('List of sports in') . ' ' . $city;
$this->headTitle($title);
echo 'current city = ' . $city;
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php foreach ($sports as $sport) : ?>
<?php
	$urlParams = array('sport' => $this->escapeHtml($sport->title), 'city' => $city);
	$aURL = $this->url('sport',  $urlParams);
	$aText =
		$this->escapeHtml($sport->title)
		. ' ' . '(' . $this->escapeHtml($sport->category) . ')'
		. ' ' . '[' . $this->escapeHtml($sport->countCourses) . ' ' . $this->translate('courses') . ']'
	;
?>
<span><a href="<?php echo $aURL; ?>"><?php echo $aText; ?></a></span>
<?php endforeach; ?>