<?php
$title = $this->translate('List of sports in') . ' ' . $city;
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<ul id="catalogListSports" class="catalogList">
<?php foreach ($sports as $sport) : ?>
	<?php
		$urlParams = array('sport' => $this->escapeHtml($sport->title), 'city' => $this->escapeHtml($city));
		$aURL = $this->url('sport',  $urlParams);
		
		$aTextCategory = !empty($sport->category)
			? ' ' . '<span class="aTextCategory">' . '(' . $this->escapeHtml($sport->category) . ')' . '</span>'
			: ''
		;
		$aTextCountCourses =
			'<span class="aTextCountCourses">'
			. ' ' . $this->escapeHtml($sport->countCourses) . ' ' . $this->translate('course(-s)')
			. '</span>'
		;
		
		$aText = $this->translate($this->escapeHtml($sport->title)) . $aTextCategory . $aTextCountCourses;
	?>
	<li><span><a href="<?php echo $aURL; ?>"><?php echo $aText; ?></a></span></li>
<?php endforeach; ?>
</ul>