<?php
use ITT\Util\Utility;
use Catalog\Model\CourseTable;
?>

<?php
if (strcasecmp($sport, CourseTable::SPORT_TITLE_UNASSIGNED)) {
	$title = sprintf($this->translate('%s in %s'), $sport, $city);
	$resultText = sprintf($this->translate('%s %s courses in %s'), $paginator->getTotalItemCount(), $sport, $city);
} else {
	$title = $this->translate('List of unassigned courses in') . ' ' . $city;
	$resultText = sprintf($this->translate('%s unassigned courses in %s'), $paginator->getTotalItemCount(), $city);
}
?>

<?php
$keywordsArray = array(
	$this->translate('courses'),
	$this->translate('list'),
	$city
);
if (strcasecmp($sport, CourseTable::SPORT_TITLE_UNASSIGNED)) {
	array_unshift($keywordsArray, $sport);
}
$this->headMeta()->setName('keywords', implode(', ', $keywordsArray));
$this->headMeta()->setName('description', $title);
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<div class="resultBlock" id="searchResultText">
	<?php echo $resultText; ?>
</div>

<?php
echo $this->paginationControl(
	$paginator, 'Sliding', 'catalog/catalog/catalog-pagination',
	array('route' => 'sport/courses', 'city' => $city, 'sport' => $sport) 
);
?>

<?php foreach ($paginator as $course) : ?>
<?php
$titleMaxLength = 40;
$courseTitle = $this->escapeHtml($course->title);
$courseTitle = !empty($courseTitle)
	? $courseTitle
	: $this->translate('Untitled')
;
$courseTitleShorted = strlen($courseTitle) > $titleMaxLength
	? substr($this->escapeHtml($courseTitle), 0, $titleMaxLength) . '...'
	: $this->escapeHtml($courseTitle)
;
?>
<?php
$courseLevel = Utility::getOneOrPair(
	$this->escapeHtml($course->uniLevelMin), $this->escapeHtml($course->uniLevelMax), ' - '
);
$courseDate = Utility::getOneOrPair(
	$this->escapeHtml($course->startDate), $this->escapeHtml($course->endDate), ' - '
);
$courseWeekday = $this->escapeHtml($course->weekday);
$courseTime = Utility::getOneOrPair(
	$this->escapeHtml($course->startTime), $this->escapeHtml($course->endTime), ' - '
);
?>
<?php
$urlParams = array('id' => $this->escapeHtml($course->id), 'title' => $this->escapeHtml($course->title));
$aURL = $this->url('course',  $urlParams);
$aText = $this->translate('course') . ' ' . $this->translate('link');
?>
<div class="resultBlock">
	<div class="resultBlockCourseIcon">K</div>
	<div class="resultBlockCourseTitle">
		<a
			href="<?php echo $aURL; ?>"
			title="<?php echo $this->escapeHtml($course->title); ?>"
		><?php echo $courseTitle; ?></a>
	</div>
	<?php if ($course->providerStatus != 'inactive') : ?>
	<div class="resultBlockCourseLevel"><?php echo $courseLevel; ?></div>
	<div class="resultBlockCourseDate"><?php echo $courseDate; ?></div>
	<div class="resultBlockCourseWeekday"><?php echo $courseWeekday; ?></div>
	<div class="resultBlockCourseTime"><?php echo $courseTime; ?></div>
	<!--div class="resultBlockSocial">[share]</div-->
	<?php else : ?>
	<div class="resultBlockCourseDisplayingForbidden">
	<?php
	echo sprintf($this->translate(
		'Unfortunately %s forbids displaying the courses information on unisport<span class="rStyle">r</span>.'
	), $course->providerName);
	?>
	</div>
	<?php endif; ?>
</div>
<?php endforeach; ?>