<?php
use ITT\Util\Utility;
use Catalog\Model\CourseTable;
?>
<?php
if (strcasecmp($sport, CourseTable::SPORT_TITLE_UNASSIGNED)) {
	$title = $sport . ' ' . $city;
} else {
	$title = $this->translate('List of unassigned courses in') . ' ' . $city;
}
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<?php foreach ($courses as $course) : ?>
<?php
$titleMaxLength = 40;
$courseTitle = $this->escapeHtml($course->title);
$courseTitle = !empty($courseTitle)
	? $courseTitle
	: $this->translate('Untitled')
;
$courseTitleShorted = strlen($courseTitle) > $titleMaxLength
	? substr($this->escapeHtml($courseTitle), 0, $titleMaxLength) . '...'
	: $this->escapeHtml($courseTitle)
;
?>
<?php
$courseLevel = Utility::getOneOrPair(
	$this->escapeHtml($course->uniLevelMin), $this->escapeHtml($course->uniLevelMax), ' - '
);
$courseDate = Utility::getOneOrPair(
	$this->escapeHtml($course->startDate), $this->escapeHtml($course->endDate), ' - '
);
$courseWeekday = $this->escapeHtml($course->weekday);
$courseTime = Utility::getOneOrPair(
	$this->escapeHtml($course->startTime), $this->escapeHtml($course->endTime), ' - '
);
?>
<?php
$urlParams = array('id' => $this->escapeHtml($course->id), 'title' => $this->escapeHtml($course->title));
$aURL = $this->url('course',  $urlParams);
$aText = $this->translate('course') . ' ' . $this->translate('link');
?>
<div class="resultBlock">
	<div class="resultBlockCourseIcon">K</div>
	<div class="resultBlockCourseTitle">
		<a
			href="<?php echo $aURL; ?>"
			title="<?php echo $this->escapeHtml($course->title); ?>"
		><?php echo $courseTitle; ?></a>
	</div>
	<div class="resultBlockCourseLevel"><?php echo $courseLevel; ?></div>
	<div class="resultBlockCourseDate"><?php echo $courseDate; ?></div>
	<div class="resultBlockCourseWeekday"><?php echo $courseWeekday; ?></div>
	<div class="resultBlockCourseTime"><?php echo $courseTime; ?></div>
	<!--div class="resultBlockSocial">[share]</div-->
</div>
<?php endforeach; ?>