<?php
// Generated by Zend Framework 2
return array(
    'Course\Module'                      => __DIR__ . '//Module.php',
    'Course\Controller\CourseController' => __DIR__ . '//src/Course/Controller/CourseController.php',
    'Course\Model\Course'                => __DIR__ . '//src/Course/Model/Course.php',
    'Course\Model\CourseTable'           => __DIR__ . '//src/Course/Model/CourseTable.php',
    'CourseTest\Bootstrap'               => __DIR__ . '//test/Bootstrap.php',
);