<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Catalog\Module'                               => __DIR__ . '/Module.php',
    'Catalog\Controller\CatalogController'         => __DIR__ . '/src/Catalog/Controller/CatalogController.php',
    'CatalogTest\Bootstrap'                        => __DIR__ . '/test/Bootstrap.php',
    'CatalogTest\Controller\CatalogControllerTest' => __DIR__ . '/test/CatalogTest/Controller/CatalogControllerTest.php',
);