<?php
// Generated by Zend Framework 2
return array(
    'Catalog\Module'                               => __DIR__ . '//Module.php',
    'Catalog\Controller\CatalogController'         => __DIR__ . '//src/Catalog/Controller/CatalogController.php',
    'Catalog\Model\City'                           => __DIR__ . '//src/Catalog/Model/City.php',
    'Catalog\Model\CityTable'                      => __DIR__ . '//src/Catalog/Model/CityTable.php',
    'Catalog\Model\Course'                         => __DIR__ . '//src/Catalog/Model/Course.php',
    'Catalog\Model\CourseTable'                    => __DIR__ . '//src/Catalog/Model/CourseTable.php',
    'Catalog\Model\Sport'                          => __DIR__ . '//src/Catalog/Model/Sport.php',
    'Catalog\Model\SportTable'                     => __DIR__ . '//src/Catalog/Model/SportTable.php',
    'Catalog\Model\University'                     => __DIR__ . '//src/Catalog/Model/University.php',
    'Catalog\Model\UniversityTable'                => __DIR__ . '//src/Catalog/Model/UniversityTable.php',
    'CatalogTest\Bootstrap'                        => __DIR__ . '//test/Bootstrap.php',
    'CatalogTest\Controller\CatalogControllerTest' => __DIR__ . '//test/CatalogTest/Controller/CatalogControllerTest.php',
    'CatalogTest\Model\CityTableTest'              => __DIR__ . '//test/CatalogTest/Model/CityTableTest.php',
    'CatalogTest\Model\CityTest'                   => __DIR__ . '//test/CatalogTest/Model/CityTest.php',
);