<?php
// Generated by Zend Framework 2
return array(
    'Application\Module'                             => __DIR__ . '//Module.php',
    'Application\Controller\IndexController'         => __DIR__ . '//src/Application/Controller/IndexController.php',
    'ApplicationTest\Controller\IndexControllerTest' => __DIR__ . '//test/ApplicationTest/Controller/IndexControllerTest.php',
    'ApplicationTest\Bootstrap'                      => __DIR__ . '//test/Bootstrap.php',
);