<?php
echo $this->doctype();
?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php
		$this->headMeta()->appendName(
			'description',
			'unisportr' . ' - ' . $this->translate('The internet resource about college sports and college sport courses')
		);
		$this->headMeta()->appendName(
			'keywords',
			implode(', ', array(
				$this->translate('sports'),
				$this->translate('universty sports'),
				$this->translate('courses'),
				$this->translate('courses search'),
				$this->translate('courses catalog')
			))
		);
		echo $this->headMeta();
		?>
		<?php echo $this->contentForEnvironment('partials/google-site-verification.phtml', ['live']); ?>
		<?php
		echo $this->headTitle(
			'unisportr' . ' - ' . $this->translate('The university sports resource')
		)->setSeparator(' - ')->setAutoEscape(false);
		?>
		<?php
		echo $this->headLink(array(
			'rel' => 'shortcut icon',
			'type' => 'image/vnd.microsoft.icon',
			'href' => $this->basePath() . '/favicon.ico'
		));
		?>
		<?php
		echo $this->headLink()
			->prependStylesheet($this->basePath() . '/css/last.css')
			->prependStylesheet($this->basePath() . '/css/parts.css')
			->prependStylesheet($this->basePath() . '/css/content.css')
			->prependStylesheet($this->basePath() . '/css/forms.css')
			->prependStylesheet($this->basePath() . '/css/navi.css')
			->prependStylesheet($this->basePath() . '/css/main.css')
			->prependStylesheet($this->basePath() . '/css/tags.css')
			->prependStylesheet($this->basePath() . '/css/default.css')
		;
		?>
		<?php
		echo $this->headScript()
			->appendFile($this->basePath() . '/js/dev.js', 'text/javascript')
			// Since the Feedeebuzz trigger JS is not working, the include is staying disabled so far.
			// ->prependFile($this->basePath() . '/js/feedeebuzz-trigger.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/search-form.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jQuery-Form/jquery.form.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jQuery-Validation/jquery.validate.min.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jQuery/jquery.min.js', 'text/javascript')
		;
		?>
	</head>
	
	<body id="bodytag">
		<div id="main">
			<div id="container">
				<div id="header">
					<div id="topMcc">
						<div id="topLeft">
							<a href="<?php echo $this->url('home') ?>" title="unisportr.com"><img
								id="logo" src="/images/logo.png"
								alt="<?php echo $this->translate('Home') ?>"
							/></a>
						</div>
						<div id="topCenter">
							<!--jdoc:include type="modules" name="search" /-->
							<?php echo $this->searhForm(); ?>
						</div>
						<div id="topRight">&nbsp;</div>
					</div>
					<div id="version"></div>
				</div>
				<div id="content">
					<div id="mcc">
						<div id="mccInner"><!-- just due the BG-bottom -->
							<div id="left">
								<div id="naviMainContainer">
									<!--jdoc:include type="modules" name="left" style="none" /-->
									<?php // echo $this->navigation('navigation')->menu(); ?>
								</div>
							</div>
							<div id="center">
								<!--jdoc:include type="modules" name="pagination" /-->
								<!--jdoc:include type="component" /-->
								<?php echo $this->content; ?>
							</div>
							<div id="right">
								<!--jdoc:include type="modules" name="right" style="none" /-->
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="footer">
				<div id="bottomMcc">
					<div id="bottomLeft"></div>
					<div id="bottomCenter">
						<div id="naviFooterContainer">
							<!--jdoc:include type="modules" name="bottom" style="none" /-->
							<?php echo $this->navigation('secondary')->menu(); ?>
						</div>
					</div>
					<div id="bottomRight"></div>
				</div>
			</div>
		</div>
		<!-- feedeebuzz /-->
		<?php echo $this->partial('partials/feedeebuzz.phtml'); ?>
		<!-- piwik -->
		<?php echo $this->contentForEnvironment('partials/piwik.phtml', ['live']); ?>
	</body>
</html>