INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Aattetur', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Alegría', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Allemande', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('American Tribal Style Belly Dance', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('An-dro', 'Kette', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('An Dro Retourné', 'Kette, offener Halbkreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Attan', 'Gruppentanz, Kreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bachata', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Baladi', 'Solotanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Balboa', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Base', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bayrisch-Polka', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Béguine', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bhangra', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bharatanatyam', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Blues', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bolero', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boogie-Woogie', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bossa Nova', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boston', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bourrée', 'Gruppentanz / Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Branle', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Breakdance', 'Einzeltanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bucimis', 'Reihe, Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bulería', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bump', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Butoh', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Calango', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cachucha', 'Einzeltanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Calypso', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cancan', 'Einzeltanz, Reihentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Canarie', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Candombe', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Capraz', 'Reihe, Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Carimbó', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Carioca', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Céilí', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cerkezko', 'offener Kreis, V-Fassung; Schulterfassung, wenn nur Männer tanzen', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ceroc', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cetvorno', 'Reihe in Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ciranda', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cha-Cha-Cha', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chacarera', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chaconne', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Charleston', 'Einzeltanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chasapiko', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chasaposervikos', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chica', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cobankat', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Contra Dance', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Courante', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Csárdás', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cueca', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cumbia', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dabke', 'Reihentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dajcovo', 'offener Kreis, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Danec', 'Reihe', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Deninka', 'Kreistanz, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Deutscher Tanz', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Discofox (auch Hustle)', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Disco Swing', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dospatsko', 'offener Kreis, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dreher', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ecossaise', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eleno mome', 'offener Kreis, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Embaga', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ententanz', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Estampie', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fackeltanz', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fandango', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Farandole', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Färöischer Kettentanz', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fest-Noz', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Finnischer Tango', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Flamenco', 'Gruppentanz mit Soli', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Furlana', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Forró', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Foxtrott', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Francaise', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gaillarde', 'Gruppenpaare', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Galopp', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gankino', 'offener Kreis, Gürtel- oder V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gavotte', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gigue', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ginka', 'offener Kreis, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Grancarsko', 'geschlossener Kreis, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Graovsko', 'Reihe in Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Guaguancó', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gummistiefel-Tanz', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Habanera', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Haka', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Halay', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hambo', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hanter dro', 'Kette', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hardstyle', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hiatamadl', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Highland Fling', 'Einzeltanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hora / Chorea', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hopak', 'Einzel-, Paar-, Gruppentanz,', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hornpipe', 'Einzeltanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hula', 'Einzel- und Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Humppa', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Isa', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jenkka', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jig', 'Einzel-, Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jive', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Joropo', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jota', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jove malaj mome', 'offener Kreis, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jumpstyle', 'Einzel- und Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kalamatianos', 'offener Halbkreis, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kasatschok', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kathak', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kathakali', 'Inszenierung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kizomba', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kontratanz', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kopanica', 'Offener Kreis, Reihe', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Koprivstica', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Krakowiak', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kuchipudi', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kreuzpolka', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kuckuckspolka', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lambada', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ländler,', 'Paartanz, Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Langsamer Walzer', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Legnala Dana', 'offener Halbkreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Letkiss', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lindy Hop', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Line Dance', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lipsi', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Long Sword Dance', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Macarena', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mahari', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mambo', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mantilatos', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mapalé', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Marinera', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mazurka', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Melbourne Shuffle', 'Einzel- und Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Menuett', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Merengue', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Messertanz', 'Gruppentanz, Zunfttanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Milonga', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Minka', 'Kreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Montuno', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Muiñeira', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Murga', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Musette', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Night Club Two Step', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Odissi', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Omal', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Onestep', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Opas', 'Männertanz, gerade Reihe, Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Orientalischer Tanz, auch Bauchtanz', 'Solotanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Palotás', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pajdusko', 'offener Kreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Para Para', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Paso Doble', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pavane', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Perreo', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pogo', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Polka', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Polonaise', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Powwow', '–', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pravo Trakijsko', 'offener Kreis, V- oder Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Quadrille', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Quickstep', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rabbitdance', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rapper Sword', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Reel', 'Gruppentanz, Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Reigen', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rheinländer', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rigaudon', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rock ’n’ Roll', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rodopsko', 'offener Halbkreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Round Dance', 'Paartanz, Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rukavice', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rumba', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Salsa', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Saltarello', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Samba', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sarabande', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sardana', 'Kreistanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Saya', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sborenka', 'Männertanz, Kreuzfassung vorn', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schäfflertanz', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schottisch', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schuhplattler', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schwerttanz', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Scottish Country Dance', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sestorka', 'Reihe von 6 Männern', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Set Dance', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sevillanas', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shag', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shim Sham', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shimmy', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shuffle', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Siciliano', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sira', 'offener Kreis, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sirtaki', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sirtos', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Slowfox', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sopsko za pojas', 'Reihe, Gürtelfassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Soukous', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Square Dance', '4 Paare', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Strathspey', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Svistovsko', 'offener Kreis, W-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Svornato', 'offener Kreis oder Reihe', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Swing', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tango (Standard)', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tango Andaluz', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tango Argentino', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tango-Walzer, Vals (Vals Cruzado)', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tango Nuevo', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tamouré', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tarantella', 'Gruppentanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tecktonik', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('The Continental', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tresterer', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tricot = An dro und Hanter dro', 'Kette', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Trite pati', 'Kreistanz, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tropanka', 'Reihe, V-Fassung', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tropnalo oro', 'offener Halbkreis', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tsifteteli', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Twist', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Two-Step', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Two Step (Round Dance)', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vals criollo', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vals Cruzado', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vari Chasapiko', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vlasko', 'offener Kreis, V-Fassung; Schulterfassung, wenn Männer alleine tanzen', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Volta', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('West Coast Swing', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Western Square Dance', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wiener Walzer', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wolosso', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zeibekiko', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zevensprong', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zonaradikos', '', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zouk', 'Paartanz', 'dance');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zweisteirer', '', 'dance');