INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('4-Cross', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('7er-Rugby', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Aerobic, Sportaerobic', 'Turnsport, Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Agility', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Aikido', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Air Hockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Airsoft', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Akontion', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Akrobatik, Sportakrobatik', 'Turnsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Allgemeines Turnen', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Alpinklettern', 'Klettern, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Amateurfunkpeilen', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('American Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('American Handball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Angelsport', 'Jagdsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Apnoetauchen', 'Tauchsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Aquaball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Aquathlon', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Arena Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Armdrücken', 'Kraftsport, Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ausdruckstanz (Modern Dance)', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Australian Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Autoball', 'Motorsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Automobilsport', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Axtwerfen', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Backgammon', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Badminton', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bahnengolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bahnradsport', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ballonfahren', 'Fliegen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ballonspiel', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bandy', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bankdrücken', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Barlauf', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Base Jumping', 'Springen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Baseball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Basketball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Baumstammwerfen', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachbasketball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachhandball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachminton', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachrugby', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachsoccer', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Beachvolleyball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bergrennen', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bergsteigen', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Biathle', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Biathlon', 'Geschwindigkeitssport, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bikebiathlon', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Billard', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Blindenfußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Blindschach', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Blitzschach', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('BMX', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bob', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boccia', 'Präzisionssport, Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bodybuilding', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bogenschießen', 'Präzisionssport, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boogie-Woogie (Tanz)', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bootschen', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bosseln (Reha-Sport)', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boßeln', 'Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bouldern', 'Klettern', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boule Lyonnaise', 'Präzisionssport, Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bowling', 'Präzisionssport, Kegelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bowls', 'Präzisionssport, Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Boxen', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Brazilian Jiu-Jitsu', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Breakdance', 'Tanzsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Brennball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bridge', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Brieftaubensport', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Broomball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Brus', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bügelspiel', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Buggykiting', 'Drachensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Buildering', 'Klettern', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bumerangwerfen', 'Jagdsport, Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Bungee-Jumping', 'Springen, Seilsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Buzkashi', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cageball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Callanetics', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Camogie', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Canadian Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Canyoning', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Carambolage', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Casting', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cheerleading', 'Turnsport, Tanzsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Chinlone', 'Tanzsport, Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Combatschießen', 'Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cricket', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cricko', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Croquet', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cross Country Racing', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Crossgolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cubbies', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Curling', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Cyclocross', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dame', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dart', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('DDC-Frisbee', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Discdogging', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Discgolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Diskuswerfen', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Distanzreiten', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dodgeball', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dogdancing', 'Tiersport, Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dogging (Sport)', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Downhill', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Drachenboot', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Drachensteigen', '', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Drag Racing', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dreisprung', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Dressurreiten', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Duathlon', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eierlaufen', 'Geschwindigkeitssport, Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Einradbasketball', 'Radsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Einradhockey', 'Radsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eishockey unter Eis', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eishockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eiskunstlauf', 'Tanzsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eisschnelllauf', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eisspeedway', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Electric Boogie', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Elefantenpolo', 'Tiersport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Elefantenrennen', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Elektrorollstuhl-Hockey', 'Torspiel, Rollstuhlsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('E-Sport', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Eurodance (Dancefloor)', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Extrembügeln', 'Extremsport, Skurrilsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Extreme Martial Arts', 'Turnsport, Akrobatik, Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fahrsport', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Falknerei', 'Jagdsport, Tierwettkampf', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skydiving (Fallschirmspringen)', 'Springen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Faustball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Faustkampf', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fechten', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Federfußball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Feldhandball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Feldhockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fingerboarding', 'Geschicklichkeitssport, Skating', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fingerhakeln', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fives', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Flag Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Flamenco', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Flossenschwimmen', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Flugmodellsport', 'Modellsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Footbag (Hacky Sack)', 'Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Footvolley', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Formelsport', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Freestyle Frisbee', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Freestyle-Skiing', 'Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Freiklettern', 'Klettern, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Friskee', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fuchsjagd', 'Jagdsport, Pferdesport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Fußballtennis', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Futsal', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gaelic Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Garde- und Schautanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gateball', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gedächtnissport', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gehen', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Geocaching', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gerätturnen', 'Turnsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gewichtheben', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gleitschirmakrobatik', 'Fliegen, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gleitschirmfliegen', 'Fliegen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Go', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Goalball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Golf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gorodki', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Grasski', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gummistiefelweitwurf', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Guts', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Gymnastik', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hahnenkampf', 'Tierwettkampf', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hallenfußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hallenhockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hammerwerfen', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Handball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Handy-Weitwurf', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Harrassenklettern', 'Klettern, Geschicklichkeit', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hill Climb', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hindernislauf', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hochsprung', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hohe Schule', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hornussen', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Horseball', 'Tiersport (Pferdesport), Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('House-Running', 'Seilsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hunderennen', 'Tierwettkampf', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hürdenlauf', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Hurling', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Indiaca', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Indoorcycling', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Inlinehockey', 'Torspiel, Skating', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Inline-Skaterhockey', 'Torspiel, Skating', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Inlineskating', 'Skating', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Inline-Speedskating', 'Skating, Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Intercrosse', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('International Rules Football', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Irish Handball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jagdsport', 'Jagdsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jahn-Wettkämpfe', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jai Alai', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jass', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jazz Dance', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jeu de palets', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jeu de Paume (Real Tennis)', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jeu Provençal', 'Präzisionssport, Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Judo', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jukskei', 'Wurfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jugger', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ju-Jutsu', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kaatsen', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kabaddi', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kamelrennen', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kaninhop', 'Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kanupolo', 'Bootssport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kanurennsport', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kanuslalom', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Karate', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kartsport', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kegelbillard', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kegeln', 'Präzisionssport, Kegelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kendo', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kickball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kickboxen', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kiiking', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kin-Ball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kitesurfen', 'Drachensport, Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kitelandboarding', 'Drachensport, Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Klettern', 'Bergsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Klippenspringen', 'Springen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Klootschießen', 'Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Klotstockspringen', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kniebeugen', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Korbball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Korfball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kraftdreikampf', 'Mehrkampfsport, Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kreuzheben', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kubb', 'Präzisionsspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kugelstoßen', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kunst- und Turmspringen', 'Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kunstflug (Flugakrobatik)', 'Fliegen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kunstradfahren', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kürbisweitwurf', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Kutterpullen', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ky?d?', 'Präzisionssport, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lacrosse', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Langbold', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Langstreckenlauf', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lapta (Spiel)', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lasergame', 'Fangspiel, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Lateinamerikanische Tänze', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Leichtathletik', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Line Dance', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Loheland-Gymnastik', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Longaméta', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Luftkissen-Schlitteln', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Luta Livre', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Merkball', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mesoamerikanisches Ballspiel', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Minigolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mittelstreckenlauf', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Moderne Schwertkunst', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Moderner Fünfkampf', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Monoski', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Motoball', 'Motorsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Motorbootsport', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Motorradsport', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mountainbike', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mountainbike-Orienteering', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Muay Thai', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Mühle', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Naturbahnrodeln', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Netball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Nippers', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Nordic Walking', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Nordische Kombination', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Novuss', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Oina', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Öl-Ringkampf', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Orientalischer Tanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Orientierungslauf', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Orientierungstauchen', 'Tauchsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Paintball', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pall Mall', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Palla eh!', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pankration', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Parkour', 'Springen, Körperkontrolle', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pato', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pelota', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Penspinning', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pentathlon', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pesäpallo', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pétanque', 'Präzisionssport, Kugelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pferderennen', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pilates', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Platzgen', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Plinking', 'Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Poker', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Polo', 'Tiersport (Pferdesport), Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Polocrosse', 'Tiersport (Pferdesport), Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pompfball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pontoniersport', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Poolbillard', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Prellball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Pultstockspringen', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Racketlon', 'Rückschlagspiel, Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rackets', '', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Racquetball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Radball', 'Radsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Radpolo', 'Radsport, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Radsport', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rafting', 'Bootssport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Raketenmodellsport', 'Modellsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rallye', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rasenkraftsport', 'Mehrkampfsport, Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rasenmähertreckerrennen', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rasenradball', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Red Bull Airrace', 'Luftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Reifenrodeln', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Reiten', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rennrodeln', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rettungssport', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rhönradturnen', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rhythmische Sportgymnastik', 'Turnsport, Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ricochet', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ringen', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ringette', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ringreiten', 'Tiersport (Pferdesport), Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ringtennis', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rinkball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Roboterfußball', 'Maschinensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rock ’n’ Roll (Tanz)', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rodeo', 'Jagdsport, Tiersport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rollhockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rollkunstlauf', 'Tanzsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rollstuhlbasketball', 'Torspiel, Rollstuhlsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rollstuhlrugby', 'Torspiel, Rollstuhlsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rollstuhltanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Roque', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Round Dance', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rounders', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rudern', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rugby League', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rugby Union', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Rundbold', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Russisches Kegeln', 'Präzisionssport, Kegelsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Savate', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Segwaypolo', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sandbahnrennen', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sandboarding', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schach', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schachboxen', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schlagball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schleuderball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schnorcheln', 'Tauchsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schwierigkeitsklettern', 'Klettern', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schwimmen', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Scoutball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Scrabble', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Seesport', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Segelfliegen', 'Fliegen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Segeln', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Seilklettern', 'Klettern', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Seilspringen', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sepak Takraw', 'Rückschlagspiel, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shaolin Kempo', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shinty', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sh?gi', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shorttrack', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Shuffleboard', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sitzball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sitzfußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sitzvolleyball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skat', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skateboarding', 'Brettsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skeleton', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ski Alpin (Abfahrtslauf, Super-G, Slalom & Riesenslalom)', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ski Nordisch', '', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skibergsteigen', 'Brettsport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skijöring', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skilanglauf', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skimboarden', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skispringen', 'Springen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skwal', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Skyrunning', 'Geschwindigkeitssport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Slackline', 'Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Slamball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sledge-Eishockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Smashball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Snooker', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Snowboard', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Snowkiting', 'Drachensport, Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Soccergolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Softball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speckbrett', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speed Flying', 'Fliegen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speedminton', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speedklettern', 'Klettern', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speersport', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Speerwerfen', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sport Stacking', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sportklettern', 'Klettern, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Schießen', 'Präzisionssport, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sportwagenrennen', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Springreiten', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sprint', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Square Dance', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Squash', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stabhochsprung', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stadionlauf', 'Geschwindigkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Staffellauf', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Standardtanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Steinstoßen', 'Kraftsport, Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Steinwerfen', 'Werfen', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stepptanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stierkampf', 'Kampfsport, Jagdsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stockball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stockschießen', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Stoolball', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Strandsegeln', '', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Straßenfußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Straßenrennen', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Street Dance', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Streetball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Streethockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Subbuteo', 'Präzisionsspiel, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Sudoku', 'Denksport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Surf Ski', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Swingolf', 'Präzisionssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Synchroneiskunstlauf', 'Tanzsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Synchronschwimmen', 'Turnsport, Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tae Bo', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Taekwondo', 'Kampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tag Rugby', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Taiji Bailong Ball', 'Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tamburello', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Taubenschießen', 'Jagdsport, Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tauchen', 'Tauchsport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tauziehen', 'Kraftsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tchoukball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tennis', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tipp-Kick', 'Präzisionsspiel, Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tischeishockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tischfußball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tischtennis', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Toboggan', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Torball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Touch (Sport)', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tourenwagen', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tractor Pulling', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Trampolinturnen', 'Turnsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Trekking', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tretze', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Trials', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Triathlon', 'Mehrkampfsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Truck-Grand-Prix', 'Motorsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Tumbling', 'Turnsport, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Twirling', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ulama (Ballspiel)', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Ultimate', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Unihockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Unterwasserhockey', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Unterwasserrugby', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Urban Freeride', 'Radsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vielseitigkeitsreiten (Military)', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vierkampf', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Vigoro', 'Schlagballspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Völkerball', 'Fangspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Volkstanz', 'Tanzsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Volleyball', 'Rückschlagspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Volleyclub', 'Rückschlagspiel, Akrobatik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Voltigieren', 'Tiersport (Pferdesport), Turnsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Waffenlauf', 'Laufsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wagenrennen', 'Tiersport (Pferdesport)', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wakeboarding', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wandern', 'Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wanderreiten', 'Tiersport (Pferdesport), Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wasserball', 'Torspiel', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wasserfahren', 'Bootssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wasserski', 'Brettsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Weitsprung', 'Leichtathletik', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wellenreiten', 'Brettsport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Westernreiten', 'Tiersport (Pferdesport), Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Windsurfen', 'Brettsport, Natursport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wokfahren', 'Schlittensport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Wurfscheibenschießen', 'Schießsport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Jo-Jo', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Yoga', 'Geschicklichkeitssport', 'sport');
INSERT IGNORE INTO sports (`title`, `category`, `type`) VALUES ('Zehnkampf, Siebenkampf', 'Leichtathletik, Mehrkampfsport', 'sport'); 