-- cities
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (1, 'Berlin');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (2, 'Erlangen');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (3, 'Nürnberg');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (6, 'Bonn');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (7, 'Aachen');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (8, 'Dresden');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (9, 'Tübingen');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (10, 'Frankfurt am Main');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (11, 'Köln');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (12, 'Göttingen');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (13, 'Kiel');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (14, 'Dortmund');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (15, 'Marburg');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (16, 'Darmstadt');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (17, 'Hannover');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (18, 'Jena');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (19, 'Karlsruhe');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (20, 'Freiburg im Breisgau');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (21, 'Duisburg');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (22, 'Bochum');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (23, 'München');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (24, 'Münster');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (25, 'Hamburg');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (26, 'Stuttgart');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (27, 'Essen');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (28, 'Leipzig');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (29, 'Würzburg');
INSERT IGNORE INTO `cities` (`id`, `name`) VALUES (30, 'Potsdam');