<?php
use ITT\Util\Utility;
?>

<div class="resultBlock" id="searchResultText">
	<?php echo sprintf($this->translate('Your search returned %s results.'), $paginator->getTotalItemCount()); ?>
</div>

<?php
echo $this->paginationControl(
	$paginator, 'Sliding', 'search/search/search-pagination',
	array('route' => 'search-courses', 'formData' => $formData) 
);
?>

<?php foreach ($paginator as $course) : ?>
<?php
$titleMaxLength = 40;
$courseTitle = $this->escapeHtml($course->title);
$courseTitle = !empty($courseTitle)
	? $courseTitle
	: $this->translate('Untitled')
;
$courseTitleShorted = strlen($courseTitle) > $titleMaxLength
	? substr($this->escapeHtml($courseTitle), 0, $titleMaxLength) . '...'
	: $this->escapeHtml($courseTitle)
;
?>
<?php
$courseLevel = Utility::getOneOrPair(
	$this->escapeHtml($course->uniLevelMin), $this->escapeHtml($course->uniLevelMax), ' - '
);
$courseDate = Utility::getOneOrPair(
	$this->escapeHtml($course->startDate), $this->escapeHtml($course->endDate), ' - '
);
$courseWeekday = $this->escapeHtml($course->weekday);
$courseTime = Utility::getOneOrPair(
	$this->escapeHtml($course->startTime), $this->escapeHtml($course->endTime), ' - '
);
?>
<?php
$urlParams = array('id' => $this->escapeHtml($course->id), 'title' => $courseTitle);
$aURL = $this->url('course',  $urlParams);
$aText = $this->translate('course') . ' ' . $this->translate('link');
?>
<div class="resultBlock">
	<div class="resultBlockCourseIcon">K</div>
	<div class="resultBlockCourseTitle">
		<a
			href="<?php echo $aURL; ?>"
			title="<?php echo $courseTitle; ?>"
		><?php echo $courseTitle; ?></a>
	</div>
	<div class="resultBlockCourseLevel"><?php echo $courseLevel; ?></div>
	<div class="resultBlockCourseDate"><?php echo $courseDate; ?></div>
	<div class="resultBlockCourseWeekday"><?php echo $courseWeekday; ?></div>
	<div class="resultBlockCourseTime"><?php echo $courseTime; ?></div>
	<!--div class="resultBlockSocial">[share]</div-->
</div>
<?php endforeach; ?>