<?php
use ITT\Util\Utility;
?>

<div class="resultBlock" id="searchResultText">
	<?php echo sprintf($this->translate('Your search returned %s results.'), $courses->count()); ?>
</div>

<?php foreach ($courses as $course) : ?>
<?php
$titleMaxLength = 40;
$courseTitle = strlen($this->escapeHtml($course->title)) > 25
	? substr($this->escapeHtml($course->title), 0, $titleMaxLength) . '...'
	: $this->escapeHtml($course->title)
;

$courseLevel = Utility::getOneOrPair(
	$this->escapeHtml($course->uniLevelMin), $this->escapeHtml($course->uniLevelMax), ' - '
);
$courseDate = Utility::getOneOrPair(
	$this->escapeHtml($course->startDate), $this->escapeHtml($course->endDate), ' - '
);
$courseWeekday = $this->escapeHtml($course->weekday);
$courseTime = Utility::getOneOrPair(
	$this->escapeHtml($course->startTime), $this->escapeHtml($course->endTime), ' - '
);
?>
<?php
$urlParams = array('id' => $this->escapeHtml($course->id), 'title' => $this->escapeHtml($course->title));
$aURL = $this->url('course',  $urlParams);
$aText = $this->translate('course') . ' ' . $this->translate('link');
?>
<div class="resultBlock">
	<div class="resultBlockCourseIcon">K</div>
	<div class="resultBlockCourseTitle">
		<a
			href="<?php echo $aURL; ?>"
			title="<?php echo $this->escapeHtml($course->title); ?>"
		><?php echo $courseTitle; ?></a>
	</div>
	<div class="resultBlockCourseLevel"><?php echo $courseLevel; ?></div>
	<div class="resultBlockCourseDate"><?php echo $courseDate; ?></div>
	<div class="resultBlockCourseWeekday"><?php echo $courseWeekday; ?></div>
	<div class="resultBlockCourseTime"><?php echo $courseTime; ?></div>
	<!--div class="resultBlockSocial">[share]</div-->
</div>
<?php if(false): ?>
<div>
	<div><a href="<?php echo $aURL; ?>"><?php echo $aText; ?></a></div>
	<div>id: <?php echo $this->escapeHtml($course->id); ?></div>
	<div>title: <?php echo $this->escapeHtml($course->title); ?></div>
	<div>description: <?php echo $this->escapeHtml($course->description); ?></div>
	<div>startDate: <?php echo $this->escapeHtml($course->startDate); ?></div>
	<div>endDate: <?php echo $this->escapeHtml($course->endDate); ?></div>
	<div>startTime: <?php echo $this->escapeHtml($course->startTime); ?></div>
	<div>endTime: <?php echo $this->escapeHtml($course->endTime); ?></div>
	<div>providerName: <?php echo $this->escapeHtml($course->providerName); ?></div>
	<div>providerType: <?php echo $this->escapeHtml($course->providerType); ?></div>
	<div>city: <?php echo $this->escapeHtml($course->city); ?></div>
	<div>weekday: <?php echo $this->escapeHtml($course->weekday); ?></div>
	<div>usrLevelMin: <?php echo $this->escapeHtml($course->usrLevelMin); ?></div>
	<div>usrLevelMax: <?php echo $this->escapeHtml($course->usrLevelMax); ?></div>
	<div>uniLevelMin: <?php echo $this->escapeHtml($course->uniLevelMin); ?></div>
	<div>uniLevelMax: <?php echo $this->escapeHtml($course->uniLevelMax); ?></div>
	<div>relevance: <?php echo $this->escapeHtml($course->relevance); ?></div>
</div>
<br />
<?php endif; ?>
<?php endforeach; ?>