<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
use Zend\Form\View\Helper\FormRadio;
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('search-courses'));
$form->prepare();
?>
<script type="text/javascript">
<!--
var formMaximized = <?php echo count($form->getMessages()) > 0 ? 'false' : 'true'; ?>;
//-->
</script>
<?php
// echo $this->headScript()->appendFile($this->basePath() . '/js/search-form.js', 'text/javascript');
?>
<?php echo $this->form()->openTag($form); ?>
	<div id="searchFormArea">
		<div id="searchFormContainer">
			<dl>
				<div id="formElementKeyword" class="formElementSet">
					<dd><?php echo $this->formRow($form->get('keyword'), null, false, false); ?></dd>
				</div>
				<div id="formElementSubmit" class="formElementSet">
					<dd><?php echo $this->formSubmit($form->get('submit')); ?></dd>
				</div>

				<div id="formElementTrainer" class="formElementSet">
					<dt><?php echo $this->formlabel($form->get('trainer')); ?></dt>
					<dd><?php echo $this->formRow($form->get('trainer'), null, false, false); ?>
				</div>
				
				<div id="formElementCity" class="formElementSet">
					<dt><?php echo $this->formlabel($form->get('city')); ?></dt>
					<dd><?php echo $this->formRow($form->get('city'), null, false, false); ?></dd>
				</div>
				<?php // Deactivated so far, since a lot of courses have no levels (NULL). ?>
				<?php if(false) : ?>
				<div id="formElementLevel" class="formElementSet formRadioSet">
					<dt><label><?php echo $this->formlabel($form->get('level')); ?></label></dt>
					<dd><?php echo $this->formRadio($form->get('level'), FormRadio::LABEL_PREPEND); ?></dd>
				</div>
				<?php endif; ?>
				<div id="formElementWeekday" class="formElementSet formCheckboxSet">
					<dt><label><?php echo $this->formlabel($form->get('weekday')); ?></label></dt>
					<dd><?php echo $this->formMultiCheckbox($form->get('weekday'), FormMultiCheckbox::LABEL_PREPEND); ?></dd>
				</div>
			</dl>
			<?php if(count($form->getMessages()) > 0): ?>
			<div id="searchFormMessagesContainer">
				<span id="searchFormMessagesHeader"><?php echo $this->translate('Please fill out the search form correctly.') ?></span>
				<ul>
				<?php foreach ($form->getMessages() as $elementName => $messages): ?>
					 <li>
					 	<span><?php echo $form->get($elementName)->getLabel(); ?></span>
					 	<ul>
					 		<?php foreach ($messages as $message): ?>
					 		<li><?php echo $this->escapeHtml($message); ?></li>
					 		<?php endforeach; ?>
					 	</ul>
					 </li>
				<?php endforeach; ?>
				</ul>
			</div>
			<?php endif; ?>
			<div class="clear"></div>
		</div>
		<input id="showFormButton" type="button" value="Suchoptionen" />
	</div>
<?php echo $this->form()->closeTag(); ?>