<?php
// Generated by Zend Framework 2
return array(
    'Search\Module'                      => __DIR__ . '//Module.php',
    'Search\Controller\SearchController' => __DIR__ . '//src/Search/Controller/SearchController.php',
    'Search\Form\CourseSearchForm'       => __DIR__ . '//src/Search/Form/CourseSearchForm.php',
    'Search\Model\Course'                => __DIR__ . '//src/Search/Model/Course.php',
    'Search\Model\CourseSearchInput'     => __DIR__ . '//src/Search/Model/CourseSearchInput.php',
    'Search\Model\CourseTable'           => __DIR__ . '//src/Search/Model/CourseTable.php',
    'Search\View\Helper\SearchForm'      => __DIR__ . '//src/Search/View/Helper/SearchForm.php',
);