<?php
// Generated by Zend Framework 2
return array(
    'Cache\Module'                  => __DIR__ . '//Module.php',
    'Cache\Model\CityStorage'       => __DIR__ . '//src/Cache/Model/CityStorage.php',
    'Cache\Model\UniversityStorage' => __DIR__ . '//src/Cache/Model/UniversityStorage.php',
);