<?php
$title = $this->translate('University sports 2.0');
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<h2 id="pageSubTitleHomeWelcome" class="pageSubTitle">Willkommen bei unisport<span class="rStyle">r</span>!</h2>

<p>unisport<span class="rStyle">r</span> ist die erste zentrale bundesweite Plattform für Hochschulsport.
Hier findest Du Kurse an derzeit
<?php echo count($universities); ?> größ<span class="rStyle">r</span>en Universitäten
in <?php echo count($cities); ?> Städten.</p>

<p>Finde Deinen Kurs mit uns<span class="rStyle">r</span>m
<a href="<?php echo $this->url('search'); ?>">Kurs-Find<span class="rStyle">r</span></a>
od<span class="rStyle">r</span> im Katalog, wo alle Kurse schön nach Stadt und (soweit möglich) Sportart soriert sind.</p>

<p>Ist Deine Stadt &mdash; also Deine Uni &mdash; nicht dabei?
Ode<span class="rStyle">r</span> wünscht Du dir eine Funktionalität,
die <p>unisport<span class="rStyle">r</span> (noch?) nicht bietet?
(Sportpartnerbörse? Kursempfehlungen? Meh<span class="rStyle">r</span> Infos rund um die Kurse?)
Ode<span class="rStyle">r</span> magst Du uns Dein Feedback geben, was Dir an der Seite gefallen oder nicht gefallen hat?</p>

<p>Schreibt uns einfach!</p>

<p>Eu<span class="rStyle">r</span> unisport<span class="rStyle">r</span> Team</p>

<p>Bisher unt<span class="rStyle">r</span>stützte Universitäten:</p>

<ul id="catalogListUniversities" class="catalogList">
<?php foreach ($universities as $university) : ?>
	<li>
		<?php
		$aURL = $this->url('city',  array('city' => $this->escapeHtml($university->cityName)));
		$aText = $this->escapeHtml($university->displayedName);
		?>
		<span><a href="<?php echo $aURL; ?>"><?php echo $aText; ?></a></span>
	</li>
<?php endforeach; ?>
</ul>