<?php
$title = $this->translate('Sitemap');
$this->headTitle($title);
?>

<h1 id="pageTitle"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$xmlFile = __DIR__ . '/../../../../../public/sitemap_local.xml';

if (!file_exists($xmlFile)) {
	throw new \Exception("File does not exist");
}

$xml = simplexml_load_file($xmlFile);

$level = 0;
foreach($xml as $url) {
	$aText = substr($url->loc, strrpos($url->loc, '/'));
	$aText = ltrim($aText, '/');
	$aText = rtrim($aText, '/');
	$aText = urldecode($aText);
	switch ($aText) {
		case 'about' :
			$aText = $this->translate('about');
		break;
		case 'catalog' :
			$aText = $this->translate('catalog');
		break;
		case 'musthead' :
			$aText = $this->translate('musthead');
		break;
		case 'search' :
			$aText = $this->translate('search');
		break;
		case 'courses' :
			$aText = $this->translate('courses');
		break;
		case 'sitemap' :
			$aText = $this->translate('sitemap');
		break;
	}
	
	$currentItem = "<li>" . "<a href=\"" . $url->loc . "\">" . $aText . "</a>" . "</li>";
	$currentItem = $aText == '/' ? '' : $currentItem;

	$echoUL = '';
	$echoLI = '';
	
	if ($aText == '' || $aText == 'stats?q=age' || $aText == 'stats?q=name') {
		continue;
	}
	
	if (substr_count($url->loc, '/') > $level) {
		$echoUL .= $level == 0 ? "<ul id=\"sitemap\">" : "<li><ul>";
		$echoLI .= $currentItem;
		$echo = $echoUL . $echoLI;
	} else if (substr_count($url->loc, '/') == $level) {
		$echoLI .= $currentItem;
		$echo = $echoLI;
	} else {
		$echoLI .= "</ul></li>";
		$echoUL .= $currentItem;
		$echo = $echoLI . $echoUL;
	}
	
	echo $echo;
	
	$level = substr_count($url->loc, '/');
}
echo "</ul>";
?>